import { writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { marked } from 'marked'

/** Strip any leading chatter before the first markdown heading. */
function cleanMarkdown(text: string): string {
  const lines = text.split('\n')
  let i = 0
  while (i < lines.length && !lines[i].trimStart().startsWith('#')) i++
  const body = (i < lines.length ? lines.slice(i) : lines).join('\n').trim()
  return body || text.trim()
}

/** Best-effort filename slug from the plan's first heading, else a fallback. */
function slugFrom(markdown: string): string {
  const h = /^#\s+(.+)$/m.exec(markdown)?.[1] ?? 'trip-plan'
  return (
    h
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'trip-plan'
  )
}

const HTML_TEMPLATE = (title: string, bodyHtml: string) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 16px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    max-width: 760px; margin: 2.5rem auto; padding: 0 1.25rem; background: #faf8f4; color: #1c1b19; }
  h1, h2, h3 { line-height: 1.25; color: #0e3b37; }
  h1 { font-size: 2rem; border-bottom: 2px solid #0e7c73; padding-bottom: .4rem; }
  h2 { margin-top: 2rem; color: #0e7c73; }
  a { color: #0e7c73; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #e3ded4; padding: .5rem .65rem; text-align: left; }
  th { background: #f1ece2; }
  code { background: #f1ece2; padding: .1rem .35rem; border-radius: 4px; }
  blockquote { border-left: 3px solid #c8911c; margin: 1rem 0; padding: .25rem 1rem; color: #5b554a; }
  hr { border: none; border-top: 1px solid #e3ded4; margin: 2rem 0; }
  .footer { margin-top: 3rem; font-size: .85rem; color: #8a8475; }
  @media (prefers-color-scheme: dark) {
    body { background: #17150f; color: #ece7da; }
    h1,h2,h3 { color: #6fd6cb; } h1 { border-color: #0e7c73; } h2 { color: #6fd6cb; }
    a { color: #6fd6cb; } th { background: #211e16; } th, td { border-color: #2c2820; }
    code { background: #211e16; } blockquote { color: #b8b1a0; }
  }
</style>
</head>
<body>
${bodyHtml}
<p class="footer">Generated by Travel AI Agent — prices and availability change; verify before booking.</p>
</body>
</html>
`

export interface SavedPlan {
  path: string
  format: 'md' | 'html'
}

/**
 * Write the agent's plan to a file the traveler can keep/share/book from.
 * Returns the absolute path written.
 */
export async function savePlan(
  rawMarkdown: string,
  format: 'md' | 'html',
  dir = join(process.cwd(), 'trips'),
): Promise<SavedPlan> {
  const md = cleanMarkdown(rawMarkdown)
  const slug = slugFrom(md)
  await mkdir(dir, { recursive: true })

  if (format === 'html') {
    const title = /^#\s+(.+)$/m.exec(md)?.[1] ?? 'Trip Plan'
    const html = HTML_TEMPLATE(title, await marked.parse(md))
    const path = join(dir, `${slug}.html`)
    await writeFile(path, html, 'utf8')
    return { path, format }
  }

  const path = join(dir, `${slug}.md`)
  await writeFile(path, md + '\n', 'utf8')
  return { path, format }
}
